### ISSUE TITLE
peer review

### ISSUE THREAD

**Issue by veramendiGabriel** [valelopee8/mercadoliebre#1]
-contiene todos los elementos
- el footer cumple con los requisitos planteados
-el sitio se adapta a los distintos tamaños de pantalla
-cuenta con el formulario de registro
-cuenta con el formulario de login
-muestra un mensaje de error al colocar información erronea
-el search bar no es un formulario
-contiene transiciones o animaciones de css

**Comment by valelopee8** [comment]
El search bar ahora es un formulario (input)
