### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by KevinDQuintana** [valelopee8/mercadoliebre#3]
- El logo del sitio aumenta su tamaño demasiado, recomiendo max-width.
- El logo del sitio no redirecciona a la pagina principal cuando se le hace click.
- La barra de busqueda no es un formulario y no se puede escribir en ella.
- El formulario de registro tiene un buen diseño.
- Los botones del formulario de registro no heredaron la fuente que se usa en todo el sitio, recomiendo declarar la fuente en el selector *{} o en el boton.
- Los botones del formulario de registro aumentan su ancho hasta ocupar todo el contenedor. Y cuando se les coloca el cursor encima este no cambia a la manito.
- El texto de los paragraph <p> del footer son demasiado pequeños, recomiendo 1rem.
- Por lo demas considero que esta muy bien la pagina.

**Comment by valelopee8** [comment]
Tamaño del logo corregido.

**Comment by valelopee8** [comment]
Logo redirecciona al home del sitio corregido.

**Comment by valelopee8** [comment]
Barra de búsqueda ahora es un formulario.

**Comment by valelopee8** [comment]
Botones corregidos.

**Comment by valelopee8** [comment]
Tamaño de los textos del footer corregido.
